### ISSUE TITLE
After upgrading from version 2.x to 3.x getting, TypeError: _connect() missing 1 ...

### ISSUE THREAD

**Issue by wilberh** [coleifer/peewee#2241]
After upgrading from version 2.x to 3.x getting, I'm getting the error below.  It worked fine in version 2.x  

```
  File "/.../lib/python3.6/site-packages/peewee.py", line 403, in inner
    with self:
  File "/.../lib/python3.6/site-packages/peewee.py", line 2936, in __enter__
    self.db.connect()
  File "/.../lib/python3.6/site-packages/peewee.py", line 3035, in connect
    self._state.set_connection(self._connect())
TypeError: _connect() missing 1 required positional argument: 'database
```

http://docs.peewee-orm.com/en/latest/peewee/database.html?highlight=Adding%20a%20new%20Database%20Driver#adding-a-new-database-driver

```
from peewee import Database
import foodb  # Our fictional DB-API 2.0 driver.


class FooDatabase(Database):
    def _connect(self, database, **kwargs):
        return foodb.connect(database, **kwargs)

def get_database_connection():
    return FooDatabase(database, **db_config)
```

**Comment by coleifer** [comment]
`_connect()` does not take a database parameter in 3.x.
