### ISSUE TITLE
Python 3.12: error: PyLongObject {aka struct _longobject} has no member named ob_digit

### ISSUE THREAD

**Issue by vkrizan** [coleifer/peewee#2720]
Peewee fails to build with Python 3.12.0a7.

```
  playhouse/_sqlite_udf.c: In function â€˜__Pyx_PyInt_AddObjCâ€™:
  playhouse/_sqlite_udf.c:5604:51: error: â€˜PyLongObjectâ€™ {aka â€˜struct _longobjectâ€™} has no member named â€˜ob_digitâ€™
   5604 |         const digit* digits = ((PyLongObject*)op1)->ob_digit;
        |                                                   ^~
  playhouse/_sqlite_udf.c: In function â€˜__Pyx_PyUnicode_Equalsâ€™:
  playhouse/_sqlite_udf.c:569:51: warning: implicit declaration of function â€˜_PyUnicode_Readyâ€™; did you mean â€˜PyUnicode_READYâ€™? [-Wimplicit-function-declaration]
    569 |                                               0 : _PyUnicode_Ready((PyObject *)(op)))
        |                                                   ^~~~~~~~~~~~~~~~
  playhouse/_sqlite_udf.c:944:43: note: in definition of macro â€˜unlikelyâ€™
    944 |   #define unlikely(x) __builtin_expect(!!(x), 0)
        |                                           ^
  playhouse/_sqlite_udf.c:6097:22: note: in expansion of macro â€˜__Pyx_PyUnicode_READYâ€™
   6097 |         if (unlikely(__Pyx_PyUnicode_READY(s1) < 0) || unlikely(__Pyx_PyUnicode_READY(s2) < 0))
        |                      ^~~~~~~~~~~~~~~~~~~~~
  playhouse/_sqlite_udf.c: In function â€˜__Pyx_Raiseâ€™:
  playhouse/_sqlite_udf.c:6584:34: error: â€˜PyThreadStateâ€™ {aka â€˜struct _tsâ€™} has no member named â€˜curexc_tracebackâ€™
   6584 |         PyObject* tmp_tb = tstate->curexc_traceback;
        |                                  ^~
  playhouse/_sqlite_udf.c:6587:19: error: â€˜PyThreadStateâ€™ {aka â€˜struct _tsâ€™} has no member named â€˜curexc_tracebackâ€™
   6587 |             tstate->curexc_traceback = tb;
        |                   ^~
  playhouse/_sqlite_udf.c: In function â€˜__Pyx_PyInt_EqObjCâ€™:
  playhouse/_sqlite_udf.c:6827:51: error: â€˜PyLongObjectâ€™ {aka â€˜struct _longobjectâ€™} has no member named â€˜ob_digitâ€™
   6827 |         const digit* digits = ((PyLongObject*)op1)->ob_digit;
        |                                                   ^~
  playhouse/_sqlite_udf.c: In function â€˜__Pyx_CLineForTracebackâ€™:
  playhouse/_sqlite_udf.c:6892:9: warning: â€˜ma_version_tagâ€™ is deprecated [-Wdeprecated-declarations]
   6892 |         __PYX_PY_DICT_LOOKUP_IF_MODIFIED(
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/python3.12/cpython/dictobject.h:22:34: note: declared here
     22 |     Py_DEPRECATED(3.12) uint64_t ma_version_tag;
        |                                  ^~~~~~~~~~~~~~
  playhouse/_sqlite_udf.c:6892:9: warning: â€˜ma_version_tagâ€™ is deprecated [-Wdeprecated-declarations]
   6892 |         __PYX_PY_DICT_LOOKUP_IF_MODIFIED(
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/python3.12/cpython/dictobject.h:22:34: note: declared here
     22 |     Py_DEPRECATED(3.12) uint64_t ma_version_tag;
        |                                  ^~~~~~~~~~~~~~
  playhouse/_sqlite_udf.c: In function â€˜__Pyx_PyInt_As_intâ€™:
  playhouse/_sqlite_udf.c:7193:53: error: â€˜PyLongObjectâ€™ {aka â€˜struct _longobjectâ€™} has no member named â€˜ob_digitâ€™
   7193 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
        |                                                     ^~
  playhouse/_sqlite_udf.c:7248:53: error: â€˜PyLongObjectâ€™ {aka â€˜struct _longobjectâ€™} has no member named â€˜ob_digitâ€™
   7248 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
        |                                                     ^~
  playhouse/_sqlite_udf.c: In function â€˜__Pyx_PyInt_As_longâ€™:
  playhouse/_sqlite_udf.c:7427:53: error: â€˜PyLongObjectâ€™ {aka â€˜struct _longobjectâ€™} has no member named â€˜ob_digitâ€™
   7427 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
        |                                                     ^~
  playhouse/_sqlite_udf.c:7482:53: error: â€˜PyLongObjectâ€™ {aka â€˜struct _longobjectâ€™} has no member named â€˜ob_digitâ€™
   7482 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
        |                                                     ^~
  playhouse/_sqlite_udf.c: In function â€˜__Pyx_PyIndex_AsSsize_tâ€™:
  playhouse/_sqlite_udf.c:7933:45: error: â€˜PyLongObjectâ€™ {aka â€˜struct _longobjectâ€™} has no member named â€˜ob_digitâ€™
   7933 |     const digit* digits = ((PyLongObject*)b)->ob_digit;
        |                                             ^~
```

GH-101291: Refactor the PyLongObject struct #101292
https://github.com/python/cpython/pull/101292
https://docs.python.org/3.12/whatsnew/3.12.html

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2192872

Thank you!

**Comment by coleifer** [comment]
3.12 is still 6 months away from being released!

That said thank you for the report. This is actually an issue with Cython. Cython optimizes access to certain CPython internals, so when an internal refactor like this occurs, Cython has to implement a complementary change.

Discussion and fix here: https://github.com/cython/cython/issues/5238

This is fixed in master for Cython and looks to be targeting the 3.0 milestone.

**Installing Cython 3.0.0b1 should resolve the problem for you on 3.12a5.**

**Comment by vkrizan** [comment]
Folks on Fedora project have rebuilt the Cython generated code and it passed the build.

**Comment by coleifer** [comment]
The C sources aren't version-controlled but I typically include them when I release, so the next release will contain updated ones. Thanks.
