### ISSUE TITLE
sqlite_ext / apsw bm25 search AND regex select

### ISSUE THREAD

**Issue by inktrap** [coleifer/peewee#2587]
I would like to combine a ranked search via sqlite-ext (bm25) on a set of documents where the content matches a regexp. It is basicly a filter, not only documents that match the search *term* are returned, but those that match the *regex* **and** (then) the search term.

Suppose I have this model:

```
from playhouse.sqlite_ext import FTS5Model, RowIDField, SearchField

class ItemIndex(FTS5Model):
    rowid = RowIDField()
    content = SearchField()

    class Meta:
        database = db
        options = {"tokenize": "porter"}
```

And a regex function like this:

```
import re
from playhouse.sqlite_ext import (SqliteExtDatabase)

def search(expr, item):
    return re.search(expr, item) is not None


db = SqliteExtDatabase("db.db", regexp_function=search)
```

Then I'll just create the table and while the functions work individually:

```
query = ItemIndex.search_bm25(search_query, with_score=True)
query = ItemIndex.select().where(ItemIndex.content.regexp(search_regex))
```

I can't chain or combine them.

Seems like the search result doesn't support select and select result don't support searches.

```
        ItemIndex.search_bm25(search_query, with_score=True)
        .select()
        .where(ItemIndex.content.regexp(search_regex))
```

```
peewee.OperationalError: near "FROM": syntax error
```

This is similar with apsw. And the other way around I'll just get `AttributeError: 'ModelSelect' object has no attribute 'search_bm25'` which I expected.

I tried to use `intersect` but then I'll get different error messages, depending on wether I'll turn scoring off or not and depending on calling `execute()` of the search query before intersecting. I don't think intersect is ment to work with search results but with another select-object anyways.

So the last idea is to get the IDs via search, then select via regex and then refine via  `.in_(value)` where `value` is the list of IDs. Then somehow get the ranking info back. That seems inefficient but doable.

How would you approach this?

**Comment by inktrap** [comment]
Facetting is typically done on the set of search results anyways, so this seems like an application for `in_`, may it be a matching regex or some attribute value that is more commonly used for facetting.

I haven't looked at it in detail but I guess sqlite_ext does a phrase search (and won't tokenize my input and just assume some operator) and thus I have to query it per-term (which is a good thing) and combine the results. But all of that is out of peewee's scope. The point is that I'll have to combine/process the search results anyways if I want a query language with operators.

**Comment by inktrap** [comment]
Yes, this is clear to me now because i read more docs. Thanks for the examples and your help! Appreciate it!
