### ISSUE TITLE
Not support self aggregate alias join any more?

### ISSUE THREAD

**Issue by BusyJay** [coleifer/peewee#506]
Hi, before release 2.4.6, I was able to find out the most recent 5 articles and its comments via:

    article = Article.select(Article).order_by(
                    Article.publish_time.desc()).paginate(1, 5).alias("ar")
    for a in Article.select(Article, Comment).join(Comment).join(
                    article, on=(Article.id==article.c.id)).aggregate_rows():
        print a

But after upgrade to 2.4.6，it raise exception as follow:

    /home/me/devenv/pyvirt/lib/python2.7/site-packages/peewee.pyc in next(self)
       1774             return inst
       1775 
    -> 1776         obj = self.iterate()
       1777         self._result_cache.append(obj)
       1778         self.__ct += 1
    
    /home/me/devenv/pyvirt/lib/python2.7/site-packages/peewee.pyc in iterate(self)
       2040                 else:
       2041                     backref = current._meta.reverse_rel_for_model(
    -> 2042                         join.dest, join.on)
       2043                     if not backref:
       2044                         continue
    
    /home/me/devenv/pyvirt/lib/python2.7/site-packages/peewee.pyc in reverse_rel_for_model(self, model, field_obj)
       3562 
       3563     def reverse_rel_for_model(self, model, field_obj=None):
    -> 3564         return model._meta.rel_for_model(self.model_class, field_obj)
       3565 
       3566     def rel_exists(self, model):
    
    AttributeError: 'SelectQuery' object has no attribute '_meta'

A quick test snippets:

    import peewee
    import datetime

    db = peewee.SqliteDatabase(":memory:")
    
    class BaseModel(peewee.Model):
        class Meta:
            database = db
    
    
    class Article(peewee.Model):
        id = peewee.PrimaryKeyField()
        publish_time = peewee.DateTimeField(default=datetime.datetime.now)
    
    
    class Comment(peewee.Model):
        id = peewee.PrimaryKeyField()
        owner_id = peewee.ForeignKeyField(Article)
    
    db.connect()
    db.create_tables([Article, Comment], True)
    
    for _ in xrange(21):
        t1 = Article.create()
        Comment.create(owner_id=t1)
        Comment.create(owner_id=t1)
    
    article = Article.select(Article).order_by(
                    Article.publish_time.desc()).paginate(1, 5).alias("ar")
    for a in Article.select(Article, Comment).join(Comment).join(
                    article, on=(Article.id==article.c.id)).aggregate_rows():
        print a

**Comment by coleifer** [comment]
Ouch, thanks! Will look into this after I get off work today.

**Comment by coleifer** [comment]
Out of curiosity, what version were you using prior to upgrading to 2.4.6?

**Comment by coleifer** [comment]
Should be fixed in f4481d14d8fc08b5c4c9964d7838af2866f021fd

**Comment by coleifer** [comment]
I'll re-push 2.4.6

**Comment by BusyJay** [comment]
verified, thx!
