### ISSUE TITLE
atomic() does not seem to have lock_type argument on 3.13.0

### ISSUE THREAD

**Issue by JeanBarriere** [coleifer/peewee#2071]
Hi !

We're using peewee on our project and we are using it with an IMMEDIATE lock type, as: 
`db.atomic(lock_type="IMMEDIATE")`

Everything was working fine on the 3.12.0, but now we have this error:

`TypeError: atomic() got an unexpected keyword argument 'lock_type'`

Any idea why ?

**Comment by williammartin** [comment]
Looks like a breaking change made here: https://github.com/coleifer/peewee/commit/36f5b4a0fef0bd236f25bf99f92f74852f219103

Perhaps the equivalent behaviour is now to pass the `lock_type` on beginning a transaction: https://github.com/coleifer/peewee/blob/master/peewee.py#L3541 ?

**Comment by coleifer** [comment]
For now try removing the keyword (lock_type) and just pass the string 'immediate'. I will put together a fix, in any case.

**Comment by coleifer** [comment]
I'm tagging a new release once the build passes. Thanks for reporting this so quickly.

**Comment by coleifer** [comment]
https://github.com/coleifer/peewee/releases/tag/3.13.1

**Comment by JeanBarriere** [comment]
Thank you for the fast update
