### ISSUE TITLE
A non-ascii field name creates a truncated attribute name

### ISSUE THREAD

**Issue by jpeloquin** [coleifer/peewee#3078]
Given a model with a field name (e.g., `θ_col`) containing non-ascii characters, peewee 4.5.1 returns None when accessing that field as an attribute. The field is instead accessible as an attribute under a truncated name (`_col`).  It also remains accessible via `Fit.select().dicts()` under the original name.  The issue appears to have been introduced in commit 6f8fd5a67aeb57440eca2dcebc84840a5f80f608

Modifying `peewee.make_identifier` to use `str.isidentifier` rather than a regex fixes the issue.  (In the example below, uncomment the monkey patch line to see the effect of this change.)

Minimum reproducible example:

```python
import peewee as pw


def make_identifier_unicode(s):
    name = s.rsplit(".", 1)[-1]
    if name.isidentifier():
        return name
    return s

# monkey-patch
# pw.make_identifier = make_identifier_unicode


db = pw.SqliteDatabase(":memory:")


class ExampleModel(pw.Model):
    θ_col = pw.TextField()

    class Meta:
        database = db


db.create_tables([ExampleModel])

ExampleModel.create(
    θ_col="foo",
)

row = ExampleModel.select().get()

print(f"{pw.__version__=}")
print(f"{ExampleModel.select().dicts().get()=}")
print()
print("Expected:")
print("row.θ_col=foo")
print(f"row._col should raise AttributeError")
print()
print("Observed:")
print(f"{row.θ_col=}")
print(f"{row._col=}")  # should raise AttributeError
```

Output with peewee 4.5.1:

```
pw.__version__='4.5.1'
ExampleModel.select().dicts().get()={'id': 1, 'θ_col': 'foo'}

Expected:
row.θ_col=foo
row._col should raise AttributeError

Observed:
row.θ_col=None
row._col='foo'
```

'Observed' output with monkey-patch:

```
Observed:
row.θ_col='foo'
AttributeError: 'ExampleModel' object has no attribute '_col'. Did you mean: 'θ_col'?
```
