### ISSUE TITLE
ManyToManyField in Shortcuts

### ISSUE THREAD

**Issue by karelv** [coleifer/peewee#502]
ManyToManyField in Shortcuts module is not working in 2.4.5

```py
from playhouse.shortcuts import ManyToManyField
```

yields in:
```
from playhouse.shortcuts import ManyToManyField
ImportError: cannot import name 'ManyToManyField'
```

So it finds the module, but not the class ManyToManyField...

Note: I refer to the example at:
http://peewee.readthedocs.org/en/latest/peewee/querying.html#manytomanyfield
Where the import statement is used.

**Comment by coleifer** [comment]
Yeah, it's currently only in master. I will be pushing a new version soon which will contain the field.
