### ISSUE TITLE
ArrayField of ForeignKeyFields, is it possible?

### ISSUE THREAD

**Issue by droserasprout** [coleifer/peewee#1771]
Hi!
I'm working with postgresql and peewee 3.7.1 and trying to initialize model's field as an array of ForeignKeyFields this way:

```python
PreviousTasks = ArrayField(ForeignKeyField, {'model': 'self', 'column_name': 'previous_tasks', 'field': 'ID', 'backref': 'TaskPreviousTasks'})
```
Docs say ArrayField argument field_class gets "a subclass of Field" so this should be possible theoretically. But I'm getting this error:
```python
  File "/opt/app/include/models/tickets.py", line 176, in <module>
    class Task(ModelBase):
  File "/opt/app/include/models/tickets.py", line 191, in Task
    PreviousTasks = ArrayField(ForeignKeyField, {'model': 'self', 'column_name': 'previous_tasks', 'field': 'ID', 'backref': 'TaskPreviousTasks'})
  File "/usr/local/lib/python3.6/site-packages/playhouse/postgres_ext.py", line 155, in __init__
    self.field_type = self.__field.field_type
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4552, in __getattr__
    if attr in self.rel_model._meta.fields:
AttributeError: 'str' object has no attribute '_meta'
```
Is there any way to do this kind of trickery or should I use PreviousTasks as an array of integers and fetch referenced models manually?

**Comment by coleifer** [comment]
I wouldn't call that trickery, I'd call it ... well, nevermind.

Just use an actual junction table. Play to the strengths of your relational database.
